### ISSUE TITLE
Locate Log Error

### ISSUE THREAD

**Issue by Bahluvisotto** [Razviar/marvelsnaptracker#11]
I was trying to download the app, but I am having the following difficulty:

-- I download in GIT the version 1.1.3 (I already disabled my AV)
-- error appears about not being able to locate the file
-- when I go to the path: "C:\Users\USERNAME\AppAppData\LocalLow
I cannot find the folder: C:\Users\USERNAME\AppAppData\LocalLow\**Second Dinner**\

![snap1](https://user-images.githubusercontent.com/34459631/206204910-c1a66693-8d51-4590-b244-c6ac570dac2a.PNG)
![snap2](https://user-images.githubusercontent.com/34459631/206204916-1d48c03b-41f5-48bd-a91f-f72805012c4c.PNG)

**Comment by Razviar** [comment]
It should be just appdata, not appappdata

Also, do you have your game from steam?

**Comment by Bahluvisotto** [comment]
Yes, from steam

That's right, I just copied it wrong:
C:\Users\USERNAME\AppData\LocalLow
![snap3](https://user-images.githubusercontent.com/34459631/206209633-c4985168-0ec9-4fee-b3bd-a201763a73b7.PNG)

**Comment by Bahluvisotto** [comment]
I have tried to locate inside these two folders, and have not been successful either
I have also looked inside the Marvel Tracker folders, but could not locate

![snap4](https://user-images.githubusercontent.com/34459631/206217172-328de9c4-fd31-4a1d-9fd7-58ac5a6209bb.PNG)


![snap5](https://user-images.githubusercontent.com/34459631/206217178-af6f2916-0803-4aed-9eac-4a7f91e5f1c2.PNG)

**Comment by DrPraxi** [comment]
Same here, cant find the "nvprod" file, tried to global search too

**Comment by sirYabar** [comment]
I have the same problem, I can't locate the log file nor the folder named "Second Dinner" in AppData/LocalLow...
