### ISSUE TITLE
[Feature Proposal] Linux support

### ISSUE THREAD

**Issue by phlawlessDevelopment** [Razviar/marvelsnaptracker#13]
I'm not sure if you're looking for any help,but I've been able to get this running fine on Ubuntu (thanks electron).

One thing I could do is make you up some details for the "readme" to explain the process of building from source (and where the files are located in the Linux files-system). This might be enough. 

Alternatively, I could package new releases for Linux so you can publish them on the releases page, I would also deal with any issues that arise from the Linux version(and help triage issues that may or may not be Linux ones).

Anyway thanks for all the great work so far.

**Comment by phlawlessDevelopment** [comment]
The newest version of Proton has this working fine on Ubuntu, I'm personally using it, along with the tracker.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Razviar** [comment]
Oh, than it makes sense! If you are willing to maintain ubuntu version, please do

**Comment by leonardogonfiantini** [comment]
If i can help in some way, please contact me i love this project and i want to run it on my ubuntu

**Comment by phlawlessDevelopment** [comment]
Hey, great to hear someone else is interested in this. I will get you an executable and instructions on how to configure this tomorrow when I'm back at my desk.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by leonardogonfiantini** [comment]
I made it works on my ubuntu, actually it's pretty easy thanks to electron, if you need help for writing instructions or modify the code i'm happy to help

**Comment by phlawlessDevelopment** [comment]
Nice, I've submitted a PR that should include the zipped binary for ubuntu, I'm working on the instructions (next day or two) and would appreciate a second opinion on some of the wording, I'll let you know when it's done.

**Comment by FherStk** [comment]
Hi there,

I compiled it myself for Ubuntu but, when I run the app, I get the following message: 
`Error: Parsing paused: we can't locate your SNAP/Standalone/States/nvprod dir. Please locate it manually in settings!` 

I wasn't able to find the nvprod folder under my steamapps path, and I'm not also sure If I should setup this as the log path...

![image](https://user-images.githubusercontent.com/324326/210546783-2a6731e2-52ef-487e-9ced-e6484775fa3d.png)

Any help would be appreciated, I know there's no official support for Ubuntu, but would be great if we can make this works. 

Thanks a lot in advance and happy new year!
Fher

P.S: I'm making a script which easily compiles the app to work under Ubuntu using an LXC/LXC container. I will share it soon :)

**Comment by leonardogonfiantini** [comment]
I'm using ubuntu 22.04 and my nvprod folder is located at: 

/steam/debian-installation/steamapps/compatdata/{steam_user}/pfx/drive_c/users/steamuser/AppData/LocalLow/Second Dinner/SNAP/Standalone/States/

You can also use this command on the terminal to find it:

sudo find / -type f -name "ProfileState.json"

This will find where is located this file which is a part of the nvprod folder.


Let me know if it works!

**Comment by FherStk** [comment]
It works!

I've just released the v1.0.0 for my Ubuntu binary builder: [https://github.com/FherStk/marvelsnaptracker-forubuntu](https://github.com/FherStk/marvelsnaptracker-forubuntu)

Thanks for all your help!
Fher

**Comment by phlawlessDevelopment** [comment]
@FherStk That's amazing !
Much better than anything I was proposing. 
If you want any help with anything going forward, I'll be around.
