### ISSUE TITLE
Can't locate logs

### ISSUE THREAD

**Issue by YellowImpulse** [Razviar/marvelsnaptracker#2]
Hi guys,

Trying to install the app, but it can't locate the logs. I haven't specified a custom location, but not sure where they might be and not sure where to look. I did a system wide search for 'Snap' and couldn't come up with anything. Looked in appdata, documents, programs and programs x86 and couldn't find any files related to snap.

**Comment by Razviar** [comment]
Hi! Normal location for logs is 
AppData\LocalLow\Second Dinner\SNAP\Standalone\States\nvprod

You should look for nvprod. Make sure hidden folders are being shown

**Comment by YellowImpulse** [comment]
Thank you. I didn't realise the app needed the game installed on the local machine to work. I've got it now, thank you!On 2 Dec 2022 11:11, Razviar ***@***.***> wrote:
Hi! Normal location for logs is
AppData\LocalLow\Second Dinner\SNAP\Standalone\States\nvprod
You should look for nvprod. Make sure hidden folders are being shown

**Comment by Jinkazama75** [comment]
I'm using Bluestacks, where can i find the nvprod path?

**Comment by Razviar** [comment]
> I'm using Bluestacks, where can i find the nvprod path?

You should get nvprod folder from BlueStacks Android image. It's located here: "/storage/emulated/0/Android/data/com.nvsgames.snap /files/Standalone/States/nvprod". Then you need to manually point the tracker to monitor that folder. When you update files in it, tracker will make uploads. But this is far from primary usage case, tracker is meant for windows Snap in the first place. So we do not recommend to use it with BlueStacks.

**Comment by Jinkazama75** [comment]
Thank you Razviar, i can extract nvprod but Bluestacks uses a vhd image, it's good for standalone read but everytime i need to update my deck i need to open vhd, it's not useful, i need to install Steam.

**Comment by XeroRestraint** [comment]
Is there a limit to the log size in the match history?  Once I get to the very bottom, results stop loading.
![Screenshot 2022-12-03 151821](https://user-images.githubusercontent.com/119752595/205460279-386574c7-4c3e-42aa-bca6-1a21adde5075.png)
