### ISSUE TITLE
Tracker does not update since 20th dec

### ISSUE THREAD

**Issue by rubelzar** [Razviar/marvelsnaptracker#25]
Hi Guys,

my tracker does not update since the initial load:

![image](https://user-images.githubusercontent.com/29301334/211529190-7ce0688c-2ff3-4a13-9f01-ebbe225b95f3.png)

I tried everything, incl. some solutions i alrteady found from similar issues (emptying cache, etc).

**Comment by Razviar** [comment]
Hello! Try to wipe and re-sync. Go to Settings -> Wipe Settings -> Repeat sync process.

**Comment by rubelzar** [comment]
Hi, already did twice

**Comment by rubelzar** [comment]
the issue is, that my data on https://marvelsnap.pro/ is not up to date either.

**Comment by LegitimateSymb** [comment]
@rubelzar Hi, try to log-out and log-in again on [](https://marvelsnap.pro/). After that, follow the steps given by @Razviar

**Comment by grayflannelsuit** [comment]
I have done all these steps and am in the same boat. No tracker or Marvel Snap Pro updates since December 11.

**Comment by grayflannelsuit** [comment]
OK I figured out my problem. I used Steam to play the game on December 11, and have only been playing on mobile since. When I logged back into Snap on Steam all my stuff updated.

**Comment by Razviar** [comment]
We are actively working on mobile tracking, soon this issue will be resolved.

**Comment by Razviar** [comment]
Mobile tracker is live: https://play.google.com/store/apps/details?id=com.mtgarenapro.snap_tracker_app
