### ISSUE TITLE
Matches no longer show Location Power totals

### ISSUE THREAD

**Issue by darkmjblink** [Razviar/marvelsnaptracker#29]
On Feb 2 at 2am ET, stats were fine, but by 10:45pm ET, stats no longer show. I believe the tracker updated to 1.1.7 during that time.

![Screenshot 2023-02-03 at 14-43-05 Marvel Snap Matches MarvelSnap pro](https://user-images.githubusercontent.com/26271420/216693555-814d10b3-46f2-4ca6-8827-7f75f60d0181.png)

**Comment by Razviar** [comment]
Thanks for raising the alarm! It's fixed in marvelsnaptracker@1.1.8
