### ISSUE TITLE
False matches

### ISSUE THREAD

**Issue by hawkian** [Razviar/marvelsnaptracker#3]
After installing the tracker but before actually playing any tracked matches, I had two mystery matches show up on my account, both recorded as losses. You can tell that they do not belong because it shows that I am using no deck, versus all the legit ones since. There's no way to remove them to get an accurate overall Win/Loss since I started tracking. 

![image](https://user-images.githubusercontent.com/8534605/205375495-70d5f948-4036-42aa-964a-b1b9c79cf4da.png)

**Comment by Razviar** [comment]
Hello! Please let me know your marvel snap user id. I'll remove those matches and will fix the issue causing such things

**Comment by hawkian** [comment]
Sure thing: 

Hawkian#28550

**Comment by Razviar** [comment]
Matches have been removed, I found the issue and fixed it too. So currently there should be no more ghost matches

**Comment by hawkian** [comment]
Just confirmed, thank you very much for jumping on it so fast!

**Comment by XeroRestraint** [comment]
Is there a limit to the match history size?  Once I get to the earliest games in my match history they appear to stop loading.

![Screenshot 2022-12-03 151821](https://user-images.githubusercontent.com/119752595/205460363-34d3a1b6-c687-4a6f-8afb-0d66814344d1.png)

**Comment by Razviar** [comment]
> Is there a limit to the match history size? Once I get to the earliest games in my match history they appear to stop loading.
> 
> ![Screenshot 2022-12-03 151821](https://user-images.githubusercontent.com/119752595/205460363-34d3a1b6-c687-4a6f-8afb-0d66814344d1.png)

This is fixed. Now you can scroll down to the bottom, and no false-loading dummy will appear.
