### ISSUE TITLE
Overlay appears, but doesn't show any data / decks

### ISSUE THREAD

**Issue by bendrexl** [Razviar/marvelsnaptracker#39]
Latest SNAP from Steam, latest tracker (1.2.9), log file location verified. The overlay shows up when SNAP has focus, but doesn't display the current deck or otherwise react to in-game events (match launch, win/loss, etc)

**Comment by bendrexl** [comment]
Unsure what changed or when, but I no longer see this issue.

**Comment by Razviar** [comment]
I released an update yesterday. The issue was related to game update, devs changed variables names we use
