### ISSUE TITLE
Minus cubes for losses are no longer calculating

### ISSUE THREAD

**Issue by XeroRestraint** [Razviar/marvelsnaptracker#4]
All defeats are showing as -0 cubes in Matches view (for me) as of Dec 03.  Last match I played showing a correct minus cube calculation was Dec 02.
![Screenshot 2022-12-03 121534](https://user-images.githubusercontent.com/119752595/205453262-c42461cb-a402-4c40-bd36-a0f111b61955.png)
![Screenshot 2022-12-03 121458](https://user-images.githubusercontent.com/119752595/205453258-2c0d4290-8dc9-4096-8620-dd47bb245ffd.png)

**Comment by Razviar** [comment]
Hi! Try to restart the tracker and check if the issue is still happening for new matches. We were fixing wrong draws, so it's possible we broke losses while fixed draws lol

**Comment by XeroRestraint** [comment]
Losses are calculating correctly after restart.  Thank you.

**Comment by Razviar** [comment]
Yep, the fix isn't retroactive

**Comment by hawkian** [comment]
Is there a way to zero out a deck to start tracking from scratch? If I delete and recreate it with the same name in the game would that work?

**Comment by Razviar** [comment]
> Is there a way to zero out a deck to start tracking from scratch? If I delete and recreate it with the same name in the game would that work?

I'm going to add a tool to zero deck's stats soon, but you can just delete it in the game and create it new, it'll work.

**Comment by Razviar** [comment]
Issue should be resolved for everyone.
