### ISSUE TITLE
Can't get account to update, tried all recommended options.

### ISSUE THREAD

**Issue by Balticus96** [Razviar/marvelsnaptracker#63]
I have the most recent version, I've tried to wipe settings and re-sync multiple times. Restarted tracker, game and PC. No errors showing up on UI, and I added the tracker as an exception for my firewall. 

![1](https://github.com/Razviar/marvelsnaptracker/assets/153949561/14391975-c7f9-4583-a1a6-5003e003b384)

![Screenshot 2023-12-15 202837](https://github.com/Razviar/marvelsnaptracker/assets/153949561/77a96ffc-740d-490b-81e0-aab776f41c0c)

The tracker is working in-game, but when I go to the marvelsnap.pro account that it's synced to, it does not update the account. The collection is empty, and recent matches don't show up.

**Comment by Balticus96** [comment]
I am so happy that the websites last solution was to send me here, and have it ignored for a month. 
Guess paying Untapped.gg money is worth it after all. Was really hoping to hop over to this tracker.

**Comment by Razviar** [comment]
Well sorry, but we don't have the support team to process all this stuff. Basically I'm the only maintainer, and I maintain not only snap project. So I don't have time to track down individual issues, I fis stuff onlly if it's broken for everyone. Tracker works for the most of users, and honestly I have no slightest idea why it didn't work for you in this particular case. So good luck with untapped. Cheers!

**Comment by Balticus96** [comment]
That is completely reasonable and fair, I just would suggest to take down the "ask on github" step on the website. No shame in not having the people or time to do that, but it's weird to offer that as an approach when it's an unrealistic expectation at the same time.
No hard feelings, was just very surprised I did not even get an "idk how to solve this" in that time, but a quick response to my childish whining.
Best of luck, and I still hope the software gets monetary support from users and the project goes well. You are making a cool thing, I'm just sad I could not get it to work.
