### ISSUE TITLE
Tracker only retains data for last 30 matches?

### ISSUE THREAD

**Issue by SkeletonKey666** [Razviar/marvelsnaptracker#7]
Is there an intended fix to only capturing the data of the 30 most recent matches? All deck stats are becoming increasingly inaccurate as older matches continuously drop off once 30 matches have been played.

**Comment by Razviar** [comment]
Stats on top of the matches page are temporarily calculated only for the matches rendered on the page. If you scroll down and load next 30 matches, you'll see that numbers are updated. We are going to replace this with overall matches stats tomorrow. 

BUT stats shown in deck details https://marvelsnap.pro/decks/?my=1 are static, so they are correct.

**Comment by SkeletonKey666** [comment]
Fantastic stuff, thanks for the quick response Raz! Keep up the phenomenal work!!

**Comment by Razviar** [comment]
At this point matches stats are rendered for all matches, not onlyt last 30.
